/*
 * This file is generated by jOOQ.
 */
package net.intergamma.stock.db.tables


import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import net.intergamma.stock.db.Public
import net.intergamma.stock.db.keys.STORE_STOCK_RESERVATION_PKEY
import net.intergamma.stock.db.keys.STORE_STOCK_RESERVATION_UKEY
import net.intergamma.stock.db.keys.STORE_STOCK_RESERVATION__STORE_STOCK_RESERVATION_STORE_ID_PRODUCT_ID_FKEY
import net.intergamma.stock.db.tables.StoreStock.StoreStockPath
import net.intergamma.stock.db.tables.records.StoreStockReservationRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * Stock of a product in a store
 */
@Suppress("UNCHECKED_CAST")
open class StoreStockReservation(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, StoreStockReservationRecord>?,
    parentPath: InverseForeignKey<out Record, StoreStockReservationRecord>?,
    aliased: Table<StoreStockReservationRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<StoreStockReservationRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment("Stock of a product in a store"),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.store_stock_reservation</code>
         */
        val STORE_STOCK_RESERVATION: StoreStockReservation = StoreStockReservation()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<StoreStockReservationRecord> = StoreStockReservationRecord::class.java

    /**
     * The column <code>public.store_stock_reservation.id</code>. System
     * generated primary key column
     */
    val ID: TableField<StoreStockReservationRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "System generated primary key column")

    /**
     * The column <code>public.store_stock_reservation.store_id</code>. The ID
     * of the store in which the product is available
     */
    val STORE_ID: TableField<StoreStockReservationRecord, String?> = createField(DSL.name("store_id"), SQLDataType.CLOB.nullable(false), this, "The ID of the store in which the product is available")

    /**
     * The column <code>public.store_stock_reservation.product_id</code>. The ID
     * of the product in the store
     */
    val PRODUCT_ID: TableField<StoreStockReservationRecord, String?> = createField(DSL.name("product_id"), SQLDataType.CLOB.nullable(false), this, "The ID of the product in the store")

    /**
     * The column <code>public.store_stock_reservation.user_id</code>. The ID of
     * the user who reserved the stock
     */
    val USER_ID: TableField<StoreStockReservationRecord, String?> = createField(DSL.name("user_id"), SQLDataType.CLOB.nullable(false), this, "The ID of the user who reserved the stock")

    /**
     * The column <code>public.store_stock_reservation.reserved_stock</code>.
     * Stock of the product in the store
     */
    val RESERVED_STOCK: TableField<StoreStockReservationRecord, Long?> = createField(DSL.name("reserved_stock"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "Stock of the product in the store")

    /**
     * The column <code>public.store_stock_reservation.expires_at</code>. The
     * timestamp when the reservation expires
     */
    val EXPIRES_AT: TableField<StoreStockReservationRecord, OffsetDateTime?> = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "The timestamp when the reservation expires")

    /**
     * The column
     * <code>public.store_stock_reservation.created_timestamp_utc</code>.
     * Metadata, timestamp when the stock record was created
     */
    val CREATED_TIMESTAMP_UTC: TableField<StoreStockReservationRecord, OffsetDateTime?> = createField(DSL.name("created_timestamp_utc"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("(now() AT TIME ZONE 'UTC'::text)"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "Metadata, timestamp when the stock record was created")

    /**
     * The column
     * <code>public.store_stock_reservation.modified_timestamp_utc</code>.
     * Metadata, timestamp when the stock record was last updated
     */
    val MODIFIED_TIMESTAMP_UTC: TableField<StoreStockReservationRecord, OffsetDateTime?> = createField(DSL.name("modified_timestamp_utc"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("(now() AT TIME ZONE 'UTC'::text)"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "Metadata, timestamp when the stock record was last updated")

    private constructor(alias: Name, aliased: Table<StoreStockReservationRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<StoreStockReservationRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<StoreStockReservationRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.store_stock_reservation</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.store_stock_reservation</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.store_stock_reservation</code> table reference
     */
    constructor(): this(DSL.name("store_stock_reservation"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, StoreStockReservationRecord>?, parentPath: InverseForeignKey<out Record, StoreStockReservationRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, STORE_STOCK_RESERVATION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class StoreStockReservationPath : StoreStockReservation, Path<StoreStockReservationRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, StoreStockReservationRecord>?, parentPath: InverseForeignKey<out Record, StoreStockReservationRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<StoreStockReservationRecord>): super(alias, aliased)
        override fun `as`(alias: String): StoreStockReservationPath = StoreStockReservationPath(DSL.name(alias), this)
        override fun `as`(alias: Name): StoreStockReservationPath = StoreStockReservationPath(alias, this)
        override fun `as`(alias: Table<*>): StoreStockReservationPath = StoreStockReservationPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<StoreStockReservationRecord, Long?> = super.getIdentity() as Identity<StoreStockReservationRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<StoreStockReservationRecord> = STORE_STOCK_RESERVATION_PKEY
    override fun getUniqueKeys(): List<UniqueKey<StoreStockReservationRecord>> = listOf(STORE_STOCK_RESERVATION_UKEY)
    override fun getReferences(): List<ForeignKey<StoreStockReservationRecord, *>> = listOf(STORE_STOCK_RESERVATION__STORE_STOCK_RESERVATION_STORE_ID_PRODUCT_ID_FKEY)

    private lateinit var _storeStock: StoreStockPath

    /**
     * Get the implicit join path to the <code>public.store_stock</code> table.
     */
    fun storeStock(): StoreStockPath {
        if (!this::_storeStock.isInitialized)
            _storeStock = StoreStockPath(this, STORE_STOCK_RESERVATION__STORE_STOCK_RESERVATION_STORE_ID_PRODUCT_ID_FKEY, null)

        return _storeStock;
    }

    val storeStock: StoreStockPath
        get(): StoreStockPath = storeStock()
    override fun `as`(alias: String): StoreStockReservation = StoreStockReservation(DSL.name(alias), this)
    override fun `as`(alias: Name): StoreStockReservation = StoreStockReservation(alias, this)
    override fun `as`(alias: Table<*>): StoreStockReservation = StoreStockReservation(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): StoreStockReservation = StoreStockReservation(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): StoreStockReservation = StoreStockReservation(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): StoreStockReservation = StoreStockReservation(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): StoreStockReservation = StoreStockReservation(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): StoreStockReservation = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): StoreStockReservation = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): StoreStockReservation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): StoreStockReservation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): StoreStockReservation = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): StoreStockReservation = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): StoreStockReservation = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): StoreStockReservation = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): StoreStockReservation = where(DSL.notExists(select))
}
