/*
 * This file is generated by jOOQ.
 */
package net.intergamma.stock.db.keys


import net.intergamma.stock.db.tables.StoreStock
import net.intergamma.stock.db.tables.StoreStockReservation
import net.intergamma.stock.db.tables.records.StoreStockRecord
import net.intergamma.stock.db.tables.records.StoreStockReservationRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val STORE_STOCK_PKEY: UniqueKey<StoreStockRecord> = Internal.createUniqueKey(StoreStock.STORE_STOCK, DSL.name("store_stock_pkey"), arrayOf(StoreStock.STORE_STOCK.ID), true)
val STORE_STOCK_UKEY: UniqueKey<StoreStockRecord> = Internal.createUniqueKey(StoreStock.STORE_STOCK, DSL.name("store_stock_ukey"), arrayOf(StoreStock.STORE_STOCK.STORE_ID, StoreStock.STORE_STOCK.PRODUCT_ID), true)
val STORE_STOCK_RESERVATION_PKEY: UniqueKey<StoreStockReservationRecord> = Internal.createUniqueKey(StoreStockReservation.STORE_STOCK_RESERVATION, DSL.name("store_stock_reservation_pkey"), arrayOf(StoreStockReservation.STORE_STOCK_RESERVATION.ID), true)
val STORE_STOCK_RESERVATION_UKEY: UniqueKey<StoreStockReservationRecord> = Internal.createUniqueKey(StoreStockReservation.STORE_STOCK_RESERVATION, DSL.name("store_stock_reservation_ukey"), arrayOf(StoreStockReservation.STORE_STOCK_RESERVATION.STORE_ID, StoreStockReservation.STORE_STOCK_RESERVATION.PRODUCT_ID, StoreStockReservation.STORE_STOCK_RESERVATION.USER_ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val STORE_STOCK_RESERVATION__STORE_STOCK_RESERVATION_STORE_ID_PRODUCT_ID_FKEY: ForeignKey<StoreStockReservationRecord, StoreStockRecord> = Internal.createForeignKey(StoreStockReservation.STORE_STOCK_RESERVATION, DSL.name("store_stock_reservation_store_id_product_id_fkey"), arrayOf(StoreStockReservation.STORE_STOCK_RESERVATION.STORE_ID, StoreStockReservation.STORE_STOCK_RESERVATION.PRODUCT_ID), net.intergamma.stock.db.keys.STORE_STOCK_UKEY, arrayOf(StoreStock.STORE_STOCK.STORE_ID, StoreStock.STORE_STOCK.PRODUCT_ID), true)
