/*
 * This file is generated by jOOQ.
 */
package net.intergamma.stock.db.tables.references


import net.intergamma.stock.db.tables.StoreStock
import net.intergamma.stock.db.tables.StoreStockReservation



/**
 * Stock of a product in a store
 */
val STORE_STOCK: StoreStock = StoreStock.STORE_STOCK

/**
 * Stock of a product in a store
 */
val STORE_STOCK_RESERVATION: StoreStockReservation = StoreStockReservation.STORE_STOCK_RESERVATION
