/*
 * This file is generated by jOOQ.
 */
package net.intergamma.stock.db


import kotlin.collections.List

import net.intergamma.stock.db.tables.StoreStock
import net.intergamma.stock.db.tables.StoreStockReservation

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * Stock of a product in a store
     */
    val STORE_STOCK: StoreStock get() = StoreStock.STORE_STOCK

    /**
     * Stock of a product in a store
     */
    val STORE_STOCK_RESERVATION: StoreStockReservation get() = StoreStockReservation.STORE_STOCK_RESERVATION

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        StoreStock.STORE_STOCK,
        StoreStockReservation.STORE_STOCK_RESERVATION
    )
}
